config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "servers#index"

  resources :servers
  resources :spares
  resources :users, controller: "admins"

  get "spare/:category", to: "spares#index", as: "spares_category"
end

app/models/server.rb
class Server < ApplicationRecord
  SERVER_LIST = [:"Storage and Memory", :"Express5800/R110i-1", :"Express5800/120h-1E", :"Express5800/R110j-1"]
  enum machine_model: SERVER_LIST

  scope :search, -> (query) { where("host_name LIKE ? OR machine_model LIKE ? OR operating_system LIKE ? OR role LIKE ? OR project LIKE ? OR date_warranty LIKE ?", "%#{query}%", "%#{query}%", "%#{query}%","%#{query}%", "%#{query}%", "%#{query}%") }

end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :set_server, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /servers
  # GET /servers.json
  def index
    @servers = params[:q] ? Server.search(params[:q]) : Server.all

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
  end

  # GET /servers/new
  def new
    @server = Server.new
  end

  # GET /servers/1/edit
  def edit
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = Server.new(server_params)

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, notice: 'Server was successfully created.' }
        format.json { render :show, status: :created, location: @server }
      else
        format.html { render :new }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servers/1
  # PATCH/PUT /servers/1.json
  def update
    respond_to do |format|
      if @server.update(server_params)
        format.html { redirect_to @server, notice: 'Server was successfully updated.' }
        format.json { render :show, status: :ok, location: @server }
      else
        format.html { render :edit }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server.destroy
    respond_to do |format|
      format.html { redirect_to servers_url, notice: 'Server was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_server
      @server = Server.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def server_params
      params.require(:server).permit(:host_name, :machine_model, :operating_system, :role, :project, :date_warranty)
    end
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/servers/_form.html.erb
<%= form_with(model: server, local: true, class: 'single', id: 'server_form') do |form| %>
  <% if server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
      <% server.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h2><%= title %></h2>

  <span>  
    <%= form.label :host_name, class: 'label'%>
    <%= form.text_field :host_name , class: 'value'%>
  </span>

  <span>
    <%= form.label :machine_model, class: 'label'%>
    <%= form.select :machine_model, Server::SERVER_LIST.collect{|i| i}, class: 'value'%>
  </span>

  <span>
    <%= form.label :operating_system, class: 'label'%>
    <%= form.text_field :operating_system, class: 'value'%>
  </span>

  <span>
    <%= form.label :role, class: 'label'%>
    <%= form.text_field :role, class: 'value'%>
  </span>

  <span>
    <%= form.label :project, class: 'label'%>
    <%= form.text_field :project, class: 'value'%>
  </span>

  <span>
    <%= form.label :date_warranty, class: 'label'%>
    <%= form.text_field :date_warranty, class: 'value'%>
  </span>

  <h3>
    <%= link_to 'Back', servers_path %> |
    <% if action_name == "edit"%>
      <%= link_to 'New', new_server_path %> <%= fa_icon("plus") %> |
    <% end %>
    <%= link_to 'Save', "", onclick: "document.getElementById('server_form').submit()" %> <%= fa_icon("save") %>
  </h3>
<% end %>

<script>
  document.addEventListener('turbolinks:load', function () {
    flatpickr('#server_date_warranty', {dateFormat: "M-d-Y"});
  })
</script>

app/views/servers/_servers.html.erb
<% servers.each do |server| %>
  <tr data-link="<%=server_path(server.id)%>">
    <%# onclick was originally for tr but then actions %>
    <td onclick="redirect(this)"><%= server.host_name %></td>
    <td onclick="redirect(this)"><%= server.machine_model %></td>
    <td onclick="redirect(this)"><%= server.operating_system %></td>
    <td onclick="redirect(this)"><%= server.role %></td>
    <td onclick="redirect(this)"><%= server.project %></td>
    <td onclick="redirect(this)"><%= server.date_warranty %></td>
    <% if current_user %>
      <td class="actions" onclick="e.stopPropagation()">
        <%= link_to fa_icon("edit"), edit_server_path(server) %>
        <%= link_to fa_icon("trash"), server, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    <% end %>
  </tr>
<% end %>

<script>
  function redirect(element) {
    var link = element.parentElement.getAttribute("data-link")
    window.location.href = this.location.origin + link
  }
</script>

app/views/servers/edit.html.erb
<%= render 'form', server: @server, title: "Editing Server" %>

app/views/servers/index.html.erb
<div class="section">
  <h2>Server List</h2>

  <%= form_for :server, remote: true, method: :get do |f| %>
    <%= text_field_tag :q, params[:q] %>
    <%= f.button fa_icon "search" %>
    <%= link_to new_server_path do %>
      <%= f.button fa_icon("plus") %>
    <% end %>
  <% end %>
</div>

<table>
  <thead>
    <tr>
      <th>Host Name</th>
      <th>Machine Model</th>
      <th>Operating System</th>
      <th>Role</th>
      <th>Project</th>
      <th>Warranty Date</th>
      <% if current_user %>
        <th>Actions</th> 
      <% end %>
    </tr>
  </thead>
  <tbody id="servers">
    <%=render partial: 'servers', locals: {servers: @servers} %>
  </tbody>
</table>

app/views/servers/index.js.erb
document.getElementById("servers").innerHTML = "<%=j render partial: 'servers', locals: {servers: @servers} %>"

app/views/servers/new.html.erb
<%= render 'form', server: @server, title: 'New Server' %>

app/views/servers/show.html.erb
<div class="single">
  <h2>Server #<%= @server.id %></h2>

  <span>
    <p class="label">Host Name</p>
    <p class="value"><%=@server.host_name%></p>
  </span>

  <span>
    <p class="label">Machine Model</p>
    <p class="value"><%=@server.machine_model%></p>
  </span>

  <span>
    <p class="label">Operating System</p>
    <p class="value"><%=@server.operating_system%></p>
  </span>

  <span>
    <p class="label">Role</p>
    <p class="value"><%=@server.role%></p>
  </span>

  <span>
    <p class="label">Project</p>
    <p class="value"><%=@server.project%></p>
  </span>

  <span>
    <p class="label">Warranty Date</p>
    <p class="value"><%=@server.date_warranty%></p>
  </span>

  <h3>
    <%= link_to 'Back', servers_path %> 
    <% if current_user %>
      | <%= link_to 'Edit', edit_server_path(@server) %> <%= fa_icon("edit") %>
    <% end %>
  </h3>
</div>