config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "servers#index"

  resources :servers
  resources :spares
  resources :users, controller: "admins"

  get "spare/:category", to: "spares#index", as: "spares_category"
end

app/models/spare.rb
class Spare < ApplicationRecord
  enum category: Server::SERVER_LIST
  
  scope :search, -> (query) { where("item_type LIKE ? OR description LIKE ? OR stock LIKE ? OR date_delivered LIKE ? OR date_warranty LIKE ? OR balance LIKE ? OR category LIKE ?", "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%") }

  def delivered
    self.date_delivered.strftime("%b %d, %Y") if self.date_delivered
  end
  
  def warranty
    self.date_warranty.strftime("%b %d, %Y") if self.date_warranty
  end
end

app/controllers/spares_controller.rb
class SparesController < ApplicationController
  before_action :set_spare, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /spares
  # GET /spares.json
  def index
    if request.path.include? "/spare/"
      spares = Spare.where(category: params[:category])
      @spares = params[:q] ? spares.search(params[:q]) : spares
    else
      @spares = params[:q] ? Spare.search(params[:q]) : Spare.all
    end
    
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /spares/1
  # GET /spares/1.json
  def show
  end

  # GET /spares/new
  def new
    @spare = Spare.new
  end

  # GET /spares/1/edit
  def edit
  end

  # POST /spares
  # POST /spares.json
  def create
    @spare = Spare.new(spare_params)

    respond_to do |format|
      if @spare.save
        format.html { redirect_to @spare, notice: 'Spare was successfully created.' }
        format.json { render :show, status: :created, location: @spare }
      else
        format.html { render :new }
        format.json { render json: @spare.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spares/1
  # PATCH/PUT /spares/1.json
  def update
    respond_to do |format|
      if @spare.update(spare_params)
        format.html { redirect_to @spare, notice: 'Spare was successfully updated.' }
        format.json { render :show, status: :ok, location: @spare }
      else
        format.html { render :edit }
        format.json { render json: @spare.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spares/1
  # DELETE /spares/1.json
  def destroy
    @spare.destroy
    respond_to do |format|
      format.html { redirect_to spares_url, notice: 'Spare was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spare
      @spare = Spare.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spare_params
      params.require(:spare).permit(:item_type ,:description ,:stock ,:date_delivered ,:date_warranty ,:balance ,:category)
    end
end

app/helpers/spares_helper.rb
module SparesHelper
end

app/views/spares/_form.html.erb
<%= form_with(model: spare, local: true, class: 'single', id: 'spare_form') do |form| %>
  <% if spare.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(spare.errors.count, "error") %> prohibited this spare from being saved:</h2>

      <ul>
      <% spare.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h2><%= title %></h2>

  <span>
    <%= form.label :item_type, class: 'label' %>
    <%= form.text_field :item_type, class: 'value' %>
  </span>

  <span>
    <%= form.label :description, class: 'label' %>
    <%= form.text_field :description, class: 'value' %>
  </span>

  <span>
    <%= form.label :stock, class: 'label' %>
    <%= form.text_field :stock, class: 'value' %>
  </span>

  <span>
    <%= form.label :date_delivered, class: 'label' %>
    <%= form.text_field :date_delivered, class: 'value' %>
  </span>

  <span>
    <%= form.label :date_warranty, class: 'label' %>
    <%= form.text_field :date_warranty, class: 'value' %>
  </span>

  <span>
    <%= form.label :balance, class: 'label' %>
    <%= form.text_field :balance, class: 'value' %>
  </span>

  <span>
    <%= form.label :category, class: 'label' %>
     <%= form.select :category, Server::SERVER_LIST.collect{|i| i}, class: 'value'%>
  </span>


  <h3>
    <%= link_to 'Back', spares_path %> |
    <% if action_name == "edit"%>
      <%= link_to 'New', new_spare_path %> <%= fa_icon("plus") %> |
    <% end %>
    <%= link_to 'Save', "", onclick: "document.getElementById('spare_form').submit()" %> <%= fa_icon("save") %>
  </h3>
<% end %>
  
<script>
  document.addEventListener('turbolinks:load', function () {
    flatpickr('#spare_date_delivered', { dateFormat: "M-d-Y" });
    flatpickr('#spare_date_warranty', {dateFormat: "M-d-Y"});
  })
</script>

app/views/spares/_spares.html.erb
<% spares.each do |spare| %>
  <tr data-link="<%=spare_path(spare.id)%>">
    <td onclick="redirect(this)"><%= spare.item_type %></td>
    <td onclick="redirect(this)"><%= spare.description %></td>
    <td onclick="redirect(this)"><%= spare.stock %></td>
    <td onclick="redirect(this)"><%= spare.date_delivered %></td>
    <td onclick="redirect(this)"><%= spare.date_warranty %></td>
    <td onclick="redirect(this)"><%= spare.balance %></td>
    <td onclick="redirect(this)"><%= spare.category %></td>

    <% if current_user %>
      <td class="actions">
        <%= link_to fa_icon("edit"), edit_spare_path(spare) %>
        <%= link_to fa_icon("trash"), spare, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
  <% end %>
  </tr>
<% end %>

<script>
  function redirect(element) {
    var link = element.parentElement.getAttribute("data-link")
    window.location.href = this.location.origin + link
  }
</script>

app/views/spares/edit.html.erb
<%= render 'form', spare: @spare, title: "Editing Spare" %>

app/views/spares/index.html.erb
<div class="section">
  <h2>Spares List</h2>

  <%= form_for :spares, remote: true, method: :get do |f| %>
    <%= text_field_tag :q, params[:q] %>
    <%= f.button fa_icon "search" %>
    <%= link_to new_spare_path do %>
      <%= f.button fa_icon("plus") %>
    <% end %>
  <% end %>
</div>

<table>
  <thead>
    <tr>
      <th>Item Type</th>
      <th>Description</th>
      <th>Stock</th>
      <th>Date Delivered</th>
      <th>Date Warranty</th>
      <th>Balance</th>
      <th>Category</th>
      <% if current_user %>
        <th>Actions</th>
      <% end %>
    </tr>
  </thead>

  <tbody id="spares">
    <%=render partial: 'spares', locals: {spares: @spares} %>
  </tbody>
</table>

app/views/spares/index.js.erb
document.getElementById("spares").innerHTML = "<%=j render partial: 'spares', locals: {spares: @spares} %>"

app/views/spares/new.html.erb
<%= render 'form', spare: @spare, title: "New Spare" %>

app/views/spares/show.html.erb
<div class="single">
  <h2>Spare #<%= @spare.id %></h2>

  <span>
    <p class="label">Item Type</p>
    <p class="value"><%= @spare.item_type %></p>
  </span>

  <span>
    <p class="label">Description</p>
    <p class="value"><%= @spare.description %></p>
  </span>

  <span>
    <p class="label">Stock</p>
    <p class="value"><%= @spare.stock %></p>
  </span>

  <span>
    <p class="label">Date Delivered</p>
    <p class="value"><%= @spare.date_delivered %></p>
  </span>

  <span>
    <p class="label">Date Warranty</p>
    <p class="value"><%= @spare.date_warranty %></p>
  </span>

  <span>
    <p class="label">Balance</p>
    <p class="value"><%= @spare.balance %></p>
  </span>

  <span>
    <p class="label">Category</p>
    <p class="value"><%= @spare.category %></p>
  </span>

  <h3>
    <%= link_to 'Back', spares_path %>
    <% if current_user %>
      | <%= link_to 'Edit', edit_spare_path(@spare) %> <%= fa_icon("edit") %>
    <% end %>
  </h3>
</div>