config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "servers#index"

  resources :servers
  resources :spares
  resources :users, controller: "admins"

  get "spare/:category", to: "spares#index", as: "spares_category"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ServerInventory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="toast">
      <% if notice %>
        <p class="notice"><%= notice %></p> 
      <% end %>
      <% if alert %>
        <p class="alert"><%= alert %></p>
      <% end %>
    </div>
    <div class="head">
      <%= content_tag(:div, (link_to "Servers", servers_path), class: active_current_path(servers_path)) %>
      <div class=<%= active_current_path(spares_path) %>> 
        <%=link_to "Spares", spares_path %>
        <ul class="dropdown">
        <% Server::SERVER_LIST.each_with_index do |server, i| %>
          <li><%= link_to server, spares_category_path(i)%></li>
        <% end%>
        </ul>
      </div>
      <% if current_user && current_user.admin?%>
        <%= content_tag(:div, (link_to "Users", users_path), class: active_current_path(users_path)) %>
      <% end %>
      <% if current_user %>
        <%= content_tag(:div, (link_to "#{current_user.full_user} | Logout", destroy_user_session_path, method: :delete)) %>
      <% else %>
        <%= content_tag(:div, (link_to "Login", new_user_session_path), class: active_current_path(new_user_session_path)) %>
      <% end %>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>